name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  EXTNAME: MixedVisibilityFiles
  MW_INSTALL_PATH: ${{ github.workspace }}

jobs:
  style-php:
    name: Code Style (PHP)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3' ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: none
          tools: composer, phpcs, phplint

      - name: Setup Extension
        uses: actions/checkout@v6

      - name: Setup Composer
        run: composer update

      - name: Lint
        run: phplint -w --exclude=vendor

      - name: PHP Code Sniffer
        run: vendor/bin/phpcs -sp --standard=.phpcs.xml .

  security:
    name: Static Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Only the versions of MediaWiki that are explicitly supported
        include:
          - php: '8.1'
            mediawiki: '1.39.15'
          - php: '8.3'
            mediawiki: '1.43.5'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, ast
          coverage: none
          tools: composer

      - name: Setup MediaWiki
        uses: actions/checkout@v6
        with:
          repository: wikimedia/mediawiki
          ref: ${{ matrix.mediawiki }}

      # Disable composer blocking of phpunit/phpunit@9.6.19, core 1.43.5 is
      # pinned to that version of phpunit and it has a vulnerability. Core was
      # updated to a newer version but that doesn't change the content of the
      # tagged version.
      - name: Bypass PHPUnit vulnerability warning
        if: ${{ matrix.mediawiki == '1.43.5' }}
        run: |
          cp composer.json composer.json.bak
          cat composer.json.bak | jq '. + {"config": ( .config + { "audit": { "ignore": { "CVE-2026-24765": "Pinned to vulnerable version" } } } ) }' > composer.json
          rm composer.json.bak

      - name: Setup Extension
        uses: actions/checkout@v6
        with:
          path: extensions/${{ env.EXTNAME }}

      - name: Setup Composer
        run: |
          echo '{"extra":{"merge-plugin":{"include":["extensions/*/composer.json","skins/*/composer.json"]}}}' > composer.local.json
          composer update
          composer update

      - name: Phan
        run: ./vendor/bin/phan -d extensions/${{ env.EXTNAME }} --minimum-target-php-version=8.1 --long-progress-bar

  test:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      MW_INSTALL_PATH: ${{ github.workspace }}/mediawiki
    strategy:
      fail-fast: false
      matrix:
        # Only the versions of MediaWiki that are explicitly supported
        include:
          - php: '8.1'
            mediawiki: '1.39.15'
          - php: '8.3'
            mediawiki: '1.43.5'
    steps:
      - name: Setup Extension
        uses: actions/checkout@v6

      - name: Mediawiki PHPUnit
        uses: wikiteq/mediawiki-phpunit-action@master
        with:
          type: extension
          php: ${{ matrix.php }}
          mwbranch: ${{ matrix.mediawiki }}
          extension: ${{ env.EXTNAME }}